Base
AymanJabr/Microverse-TNW-Clone pull request #2
Opened 2021-01-20 13:03 UTC by AymanJabr

Styled the Html page with 3 separate styles for different screens. 
One for a phone with max width: 768px
One for tablets with max width: 1024px
One for pc with bigger screens

2021-01-20 16:53 UTC, MuriloRoque requested changes
## Status: Changes requested :red_circle: 

### Hello @AymanJabr and @vidhishweta01 :wave: 

### You did such an amazing job on this project, I'm very proud of you! Congratulations :clap: :clap: :clap: 

### There are only some very minor issues to solve, but they are intended to improve your code and make it cleaner. Please check my comments in your code.

Kindly make the requested changes and submit them for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2021-01-20 16:53 UTC, MuriloRoque commented on styles.css
> +}
- [ ] In here you have two options to make your code cleaner:
- a) Make a class named `d-none` or similar with `display: none` and apply it to these elements you want or;
- b) Put the class names in the same line separated with a comma, then apply `display: none` to them at the same time.

2021-01-20 16:53 UTC, MuriloRoque commented on styles.css
> +  }
- [ ] In here you have two options to make your code cleaner:
- a) Make a class named `f-17` or similar with `font-size: 17px` and apply it to these elements you want or;
- b) Put the class names in the same line separated with a comma, then apply `font-size: 17px` to them at the same time.

2021-01-21 04:40 UTC, arslanbisharat requested changes
### Request Changes
Please remove linter errors and then request for a code review.

Best,
Arslan Bisharat
Slack:arslanbisharat

2021-01-21 06:33 UTC, AymanJabr commented
Linter errors are from netlify and not from the Microverse linter.

On Thu, Jan 21, 2021 at 6:40 AM Arslan Bisharat <notifications@github.com>
wrote:

> *@arslanbisharat* requested changes on this pull request.
> Request Changes
>
> Please remove linter errors and then request for a code review.
>
> Best,
> Arslan Bisharat
> Slack:arslanbisharat
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/AymanJabr/Microverse-TNW-Clone/pull/2#pullrequestreview-572978426>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJXK3IQRB5VVTQNYDSXQ2GDS26V37ANCNFSM4WKUUGGQ>
> .
>

2021-01-21 07:04 UTC, PhillipUg approved these changes
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this project approved. :+1:

You can merge this branch into the main branch when you're ready and go on to your next project.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

2021-01-21 07:09 UTC, merged